version: 2.1

jobs:
  test:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Test
          command: |
            echo 'Running test command'

  terraform_plan:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform_apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform_plan_destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform_destroy:
    docker: 
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy

workflows:
  example:
    jobs:
      - test
      - terraform_plan
      - terraform_apply_approval:
          type: approval
          requires:
            - terraform_plan
      - terraform_apply:
          requires:
            - terraform_apply_approval
      - terraform_plan_destroy:
          requires:
            - terraform_apply
      - terraform_destroy_approval:
          type: approval
          requires:
            - terraform_plan_destroy
      - terraform_destroy:
          requires:
            - terraform_destroy_approval
