version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0
  terraform: circleci/terraform@3.0.1

jobs:
  setup:
    docker:
      - image: cimg/node:17.5.0
    steps:
      - checkout
      - run: npm i
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/node:17.5.0
    steps:
      - attach_workspace:
          at: .
      - run: npm test

  build:
    docker:
      - image: cimg/node:17.5.0
    steps:
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: dist/www
          to: 's3://www.twowheeledadventuretours.com'

workflows:
  deploy_site:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup
      - approve_deploy:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - approve_deploy
